name: Software composition analysis (SCA)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  Build_Publish_Stage:
    runs-on: ubuntu-latest
    name: Build, Publish, and Stage
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        npm install --global @cyclonedx/cyclonedx-npm
        npm i -g typescript ts-node
        npm install --production --unsafe-perm
        npm dedupe
      shell: bash
    - name: Create BOM
      run: |
        npm install -g @cyclonedx/cyclonedx-npm@latest
        npm run sbom
      shell: bash
    - name: Upload BOM to Dependency-Track
      run: |
        curl -v -X "POST" "https://dependency-track-devsecops-${{ secrets.LABINSTANCEID }}.azurewebsites.net/api/v1/bom" \
             -H 'Content-Type: multipart/form-data' \
             -H 'X-API-Key: ${{ secrets.DTRACKAPIKEY }}' \
             -F 'project=project2' \
             -F 'autoCreate=true' \
             -F 'bom=@${{ github.workspace }}/bom.xml'
      continue-on-error: true
    - name: Upload BOM to Dependency-Track
      # You may pin to the exact commit or the version.
      # uses: DependencyTrack/gh-upload-sbom@48feab3080ff9e8f51f4d21861d9fc914eb744f5
      uses: DependencyTrack/gh-upload-sbom@v3.1.0
      with:
        # Dependency-Track hostname
        serverhostname: dependency-track-devsecops-47526599.azurewebsites.net
        # Dependency-Track API key
        apikey: ${{ secrets.DTRACKAPIKEY }}
        # Project in Dependency-Track
        project: DevSecOps2
        # Project name in Dependency-Track
        projectname: DevSecOps2 
        # Automatically create the project in Dependency-Track if it doesn't exist
        autocreate: true # optional, default is false
        # Path and filename of the BOM
        bomfilename: ${{ github.workspace }}/bom.xml

                    
